config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)" do
    devise_for :users,
      controllers: {
        registrations: 'users/registrations',
      },
      defaults: {
        locale: I18n.locale,
      }

    resources :events, shallow: true do
      member do
        get 'ical'
      end

      collection do
        get 'rsvped', to: 'events#attendee_index'
      end

      resources :comments, only: [:create, :update, :destroy] do
        member do
          put 'undelete'
          post 'reply', to: 'comments#create_reply'
        end
      end

      resources :attendances, only: [:create, :update, :destroy]
      resources :polls, except: [:index, :show], shallow: true do
        resources :poll_responses, only: [:create, :update, :destroy]
      end
    end

    resources :addresses, only: [
      :show,
      # only for testing
      :create,
    ]


    # user-scoped events index
    resources :user, shallow: true, only: [] do
      resources :addresses, only: [:create]
      resources :events, only: [:index]
    end

    resources :mailing_lists do
      member do
        put 'sync_users'
      end
    end

    root "home#index"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event

  belongs_to :creator, polymorphic: true
  belongs_to :editor, polymorphic: true, optional: true

  belongs_to :parent, class_name: "Comment", optional: true
  has_many :children, class_name: "Comment", foreign_key: :parent_id

  def deleted?
    deleted_at.present?
  end

  def edited?
    !editor.nil?
  end

  def deletable_by?(user)
    creator == user or event.hosted_by?(user)
  end

  def editable_by?(user)
    creator == user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user_or_guest_auth
  before_action :set_event, only: [:create]
  before_action :set_parent, only: [:create_reply]
  before_action :set_manageable_comment, only: [:update, :destroy, :undelete]

  # TODO event owners should not have global edit permissions
  def update
    if @comment.update(comment_params.merge(editor: @authenticated_user))
      message = {notice: t('comment.updated')}
    else
      message = {alert: t('comment.updated_failed') + "#{@comment.errors}"}
    end

    redirect_to event_path(@comment.event, guest_guid: params[:guest_guid]), message
  end

  def destroy
    if @comment.update(deleted_at: Time.current, editor: @authenticated_user)
      message = {notice: t('comment.destroyed')}
    else
      message = {alert: t('comment.destroyed_failed')}
    end

    redirect_to event_path(@comment.event, guest_guid: params[:guest_guid]), message
  end

  def undelete
    if @comment.update(deleted_at: nil, editor: @authenticated_user)
      message = {notice: t('comment.undeleted')}
    else
      message = {alert: t('comment.undeleted_failed')}
    end

    redirect_to event_path(@comment.event, guest_guid: params[:guest_guid]), message
  end

  def create
    @comment = @event.comments.build(comment_params.merge(creator: @authenticated_user))

    if @comment.save
      message = {notice: t('comment.created')}
    else
      message = {alert: t('comment.created_failed') + "#{@comment.errors}"}
    end

    redirect_to event_path(@comment.event, guest_guid: params[:guest_guid]), message
  end

  def create_reply
    @comment = @parent_comment.children.build(comment_params.merge(
      event: @parent_comment.event,
      creator: @authenticated_user,
    ))

    if @comment.save
      message = {notice: t('comment.created')}
    else
      message = {alert: t('comment.created_failed') + "#{@comment.errors}"}
    end

    redirect_to event_path(@comment.event, guest_guid: params[:guest_guid]), message
  end

  private

  def require_user_or_guest_auth
    unless @authenticated_user
      redirect_to new_user_session_path, alert: t('comment.rejection.unauthenticated')
      return
    end
  end

  def set_manageable_comment
    begin
      @comment = @authenticated_user.comments.includes(:event, :editor).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      # if the user didn't make the comment, they can still edit/delete it
      # if they're the owner of the event the comment was posted on.
      target_comment = Comment.includes(:event, :editor).find(params[:id])
      if !@authenticated_user.guest? and target_comment.event.hosted_by?(@authenticated_user)
        @comment = target_comment
      else
        raise
      end
    end
  end

  def set_parent
    @parent_comment = Comment.includes(:creator, :event).find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_event
    @event = Event.friendly.find(params[:event_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def children_from(parent_comment, comments)
    comments.select{|c| c.parent_id == parent_comment.id }
  end
end

app/views/comments/_comment.html.haml
:ruby
  # Views that use this partial must supply the following variables:
  # comment - the comment to be rendered
  # comments - nested comment tree created by event.comment_tree

.card.comment.m-2{id: "comment-#{comment.id}"}
  .card-body{class: (comment.deleted? && 'text-muted em')}
    %strong.author= comment.creator.name
    %small
      %span.timestamp
        = comment.created_timestamp
      %span.timestamp
        - if comment.deleted?
          - deletion_title = comment.editor == comment.creator ? "" : t('comment.view.deleted_by', editor: comment.editor.try(:name))
          %strong{title: deletion_title, data: {toggle: 'tooltip', placement: 'right'}}= t('comment.view.deleted')
        - elsif comment.edited?
          %span{title: comment.updated_timestamp, data: {toggle: 'tooltip', placement: 'right'}} ✏️
    - unless comment.deleted?
      %span.avatar.float-start.mt-2.me-3.mb-1
        = image_tag(comment.creator.gravatar_url, alt: comment.creator.name, title: comment.creator.name, border: 1)
    - if comment.deleted?
      %span.actions
        .float-end
          .btn-group
            - if comment.deletable_by?(@authenticated_user)
              = link_to t("comment.actions.undelete"), undelete_comment_path(comment, guest_guid: params[:guest_guid]), method: :put, class: "undelete-button btn btn-sm btn-danger", remote: false
    - else
      .comment-body.body{id: "comment-#{comment.id}-body"}
        = comment.rendered_body
      - if comment.editable_by?(@authenticated_user)
        .edit-form{id: "comment-#{comment.id}-edit"}
          = render 'comments/form', comment: comment
    .clearfix
    - if @authenticated_user and !comment.deleted?
      .reply-form{data: {id: comment.id}}
        = render 'comments/form', parent_comment: comment
      %span.actions
        .float-end
          .btn-group
            - if comment.editable_by?(@authenticated_user)
              %a.edit-button.btn.btn-sm.btn-primary{id: "comment-#{comment.id}-edit-button", data: {id: comment.id}}= t('comment.actions.edit')
            - if comment.deletable_by?(@authenticated_user)
              = link_to t("comment.actions.delete"), comment_path(comment, guest_guid: params[:guest_guid]), data: { confirm: t('comment.actions.confirm_delete') }, method: :delete, class: "btn btn-sm btn-danger delete-button", remote: false
        .float-start
          %a.btn.btn-sm.btn-primary.reply-button{data: {id: comment.id}}= t('comment.actions.reply')
    .clearfix
    .section.bottom
    .children
      = render children_from(comment, comments), comments: comments

app/views/comments/_form.html.haml
:ruby
  comment ||= Comment.new
  parent_comment ||= nil
  if parent_comment
    object = comment
    path = reply_comment_path(parent_comment)
    target_id = parent_comment.id
    cancel_class = "cancel-reply"
  elsif comment.new_record?
    object = [event, comment]
    target_id = "new"
    cancel_class = "cancel-comment"
  else
    object = comment
    target_id = comment.id
    cancel_class = "cancel-edit"
  end
- if comment.errors.any?
  .error-explanation
    %h3= t "comment.errors.#{new_record ? 'create' : 'update'}"
    %ul
      - comment.errors.full_messages.each do |msg|
        %li= msg
.m-2
  = form_with(model: object, url: path, remote: false) do |form|
    = form.hidden_field :parent_id
    = hidden_field_tag :guest_guid, params[:guest_guid]
    - unless parent_comment.nil?
      .replying
        %em= t('comment.view.reply_designation', parent_creator: parent_comment.creator.name)
    .field
      = form.text_area :body, rows: '7', class: 'form-control'
    .submit
      = form.submit t('submit'), class: 'btn btn-primary'
      %a.btn.btn-default{class: cancel_class, data: {id: target_id}}= t('cancel')