config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)" do
    devise_for :users,
      controllers: {
        registrations: 'users/registrations',
      },
      defaults: {
        locale: I18n.locale,
      }

    resources :events, shallow: true do
      member do
        get 'ical'
      end

      collection do
        get 'rsvped', to: 'events#attendee_index'
      end

      resources :comments, only: [:create, :update, :destroy] do
        member do
          put 'undelete'
          post 'reply', to: 'comments#create_reply'
        end
      end

      resources :attendances, only: [:create, :update, :destroy]
      resources :polls, except: [:index, :show], shallow: true do
        resources :poll_responses, only: [:create, :update, :destroy]
      end
    end

    resources :addresses, only: [
      :show,
      # only for testing
      :create,
    ]


    # user-scoped events index
    resources :user, shallow: true, only: [] do
      resources :addresses, only: [:create]
      resources :events, only: [:index]
    end

    resources :mailing_lists do
      member do
        put 'sync_users'
      end
    end

    root "home#index"
  end
end

app/views/partials/_add_fields_button.html.haml
- # required variables:
- #   form: a form object for the PARENT of the objects being managed in the list
- #   label: the text to put on the button being created
- #   item_name: the name of the model being managed, as a symbol in snake_case
- # optional variables:
- # target: an anchor for a div to append new instances of the form to. defaults to "##{plural_item_name}"

- plural_item_name = item_name.to_s.pluralize
- kebab_item_name = item_name.to_s.dasherize
- target ||= "##{plural_item_name}"

= link_to_add_fields label, form, plural_item_name.intern, {partial: "#{plural_item_name}/form", target: target, locals: { item_name => form.object.send(plural_item_name.intern).build }, layout: :inline, child_index: "added_#{item_name}"}, class: 'btn btn-success', id: "add-#{kebab_item_name}"

app/views/partials/_checkbox.html.haml
- message ||= ''
= form.check_box field_name, label: label, label_class: 'btn btn-outline-dark', class: 'marked-checkbox btn-check', wrapper_class: 'd-inline-block'
- if message.present?
  = render "shared/info_tooltip", message: message

app/views/partials/_dynamic_list_form_field.html.haml
- # required variables:
- # f: a form object for the record in question
- # item_name: the snake_case name of this type of item, e.g. signup_sheet_item
- # fields: a list of symbolized names of text fields to render for each item.

- row_id = f.object.persisted? ? "#{item_name}_#{f.object.id}" : "#{item_name}__timestamp_"
- if f.object.errors.any?
  %div{class: "#{item_name}_error_explanation_#{f.object.id}"}
    %h2= t("#{item_name}.form.errors_msg", count: f.object.errors.count)
    %ul
      - f.object.errors.full_messages.each do |message|
        %li= message
= f.form_group layout: :inline, class: 'row', "id" => row_id, data: {persisted: (!f.object.new_record?).to_s} do
  = f.hidden_field :id, value: f.object.id unless f.object.new_record?
  = f.hidden_field :_destroy, class: 'destroy', value: 0
  .input-group
    - fields.each do |field|
      = f.text_field field, floating: true
    %button.btn.btn-danger.dynamic-list-delete{data: {dynamic_target_id: row_id}, onclick: "return false;"} X

  = yield row_id

app/views/partials/_navbar.html.haml
%nav.navbar.navbar-expand-md.navbar-light.bg-light{role: :navigation, 'aria-label': "main navigation"}
  .container-fluid
    = link_to "Parties for All", root_path, class: "navbar-brand"
    .dropdown
      %button.btn.dropdown-toggle{type: 'button', id: 'locale-dropdown', data: {'bs-toggle': 'dropdown'}}= current_locale_emoji
      %ul.dropdown-menu{aria: {labelledby: 'locale-dropdown'}}
        %li.dropdown-item
          = link_to "🇺🇸 English (United States)", url_for(params.permit!.merge(locale: :en)), class: 'text-decoration-none'
        %li.dropdown-item
          = link_to "#{locale_emoji(:es)} Español (Latinoamerica)", url_for(params.permit!.merge(locale: :es)), class: 'text-decoration-none'
    %button.navbar-toggler{type: 'button', data: {'bs-toggle': 'collapse', 'bs-target': '#main-nav'}, aria_controls: 'main-nav', aria_expanded: false, aria_label: "Toggle navigation"}
      %span.navbar-toggler-icon
    .collapse.navbar-collapse#main-nav
      %ul.navbar-nav.me-auto
        %li.nav-item= link_to t('navbar.home'), root_path, class: 'nav-link'
        - if user_signed_in?
          %li.nav-item.dropdown
            %a.nav-link.dropdown-toggle#host-dropdown{href: '#', role: 'button', data: {'bs-toggle': 'dropdown'}, aria: {haspopup: 'true', expanded: 'false'}}= t('navbar.host.header')
            .dropdown-menu{aria: {labelledBy: 'host-dropdown'}}
              = link_to t('navbar.host.organize'), new_event_path, class: "dropdown-item text-bg-primary"
              = link_to t('navbar.host.my_events'), user_events_path(current_user), class: "dropdown-item"
              = link_to t('navbar.host.mailing_lists'), mailing_lists_path, class: "dropdown-item"
          %li.nav-item.dropdown
            %a.nav-link.dropdown-toggle#attendee-dropdown{href: '#', role: 'button', data: {'bs-toggle': 'dropdown'}, aria: {haspopup: 'true', expanded: 'false'}}= t('navbar.attendee.header')
            .dropdown-menu{aria: {labelledBy: 'attendee-dropdown'}}
              = link_to t('navbar.attendee.public_events'), events_path, class: "dropdown-item"
              = link_to t('navbar.attendee.rsvped_events'), rsvped_events_path, class: 'dropdown-item'
          %li.nav-item= link_to t('navbar.profile'), edit_user_registration_path, class: "nav-link"
          %li.nav-item= button_to t('navbar.log_out'), destroy_user_session_path, method: :delete, class: "nav-link btn btn-link"
        - else
          %li.nav-item= link_to t('navbar.log_in'), new_user_session_path(locale: I18n.locale), class: "nav-link"
      .navbar-nav.d-flex
        .nav-link= t('navbar.byline.message', repo_link: link_to(t('navbar.byline.repo_link_msg'), "https://www.github.com/ThePletch/shay-parties", class: 'text-decoration-none'), personal_link: link_to(t('navbar.byline.personal_link_msg'), "https://shay.zone", class: 'text-decoration-none')).html_safe

app/views/partials/_still_translating.html.haml
- if I18n.locale != :en
  = link_to t('still_translating'), url_for(params.permit!.merge(locale: :en)), class: 'text-decoration-none'