config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)" do
    devise_for :users,
      controllers: {
        registrations: 'users/registrations',
      },
      defaults: {
        locale: I18n.locale,
      }

    resources :events, shallow: true do
      member do
        get 'ical'
      end

      collection do
        get 'rsvped', to: 'events#attendee_index'
      end

      resources :comments, only: [:create, :update, :destroy] do
        member do
          put 'undelete'
          post 'reply', to: 'comments#create_reply'
        end
      end

      resources :attendances, only: [:create, :update, :destroy]
      resources :polls, except: [:index, :show], shallow: true do
        resources :poll_responses, only: [:create, :update, :destroy]
      end
    end

    resources :addresses, only: [
      :show,
      # only for testing
      :create,
    ]


    # user-scoped events index
    resources :user, shallow: true, only: [] do
      resources :addresses, only: [:create]
      resources :events, only: [:index]
    end

    resources :mailing_lists do
      member do
        put 'sync_users'
      end
    end

    root "home#index"
  end
end

app/models/mailing_list.rb
class MailingList < ApplicationRecord
  belongs_to :user
  has_many :emails, class_name: "MailingListEmail", dependent: :destroy

  validates :name, presence: true

  accepts_nested_attributes_for :emails, allow_destroy: true

  # links any emails that match existing users to those users
  def sync_users(force: false)
    emails.each{|email| email.match_to_user(force: force) }
  end
end

app/controllers/mailing_lists_controller.rb
class MailingListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_mailing_list, only: [:show, :edit, :update, :destroy, :sync_users]

  def index
    @mailing_lists = current_user.mailing_lists
  end

  def show
    case params[:scope]
    when 'exclude_no_rsvps'
      event = current_user.managed_events.find(params[:event_id])
      @emails = @mailing_list.emails.no_decline_rsvp_for_event(event)
    when 'attendees'
      event = current_user.managed_events.find(params[:event_id])
      @emails = @mailing_list.emails.attending_event(event)
    else
      @emails = @mailing_list.emails
    end
  end

  def new
    @mailing_list = MailingList.new
  end

  def edit
  end

  def create
    @mailing_list = current_user.mailing_lists.build(mailing_list_params)

    if @mailing_list.save
      redirect_to @mailing_list, notice: t('mailing_list.created')
    else
      render :new
    end
  end

  def update
    if @mailing_list.update(mailing_list_params)
      redirect_to @mailing_list, notice: t('mailing_list.updated')
    else
      render :edit
    end
  end

  def destroy
    @mailing_list.destroy
    redirect_to events_url, notice: t('mailing_list.destroyed')
  end

  def sync_users
    @mailing_list.sync_users
    redirect_to @mailing_list, notice: t('mailing_list.synced')
  end

  private

  def set_mailing_list
    @mailing_list = current_user.mailing_lists.includes(:emails).find(params[:id])
  end

  def mailing_list_params
    params.require(:mailing_list).permit(:name, emails_attributes: [:_destroy, :id, :email])
  end
end

app/views/mailing_lists/_form.haml
- if mailing_list.persisted?
  = button_to t('mailing_list.form.delete'), mailing_list_path(mailing_list), method: :delete, class: 'btn btn-danger float-end', data: {confirm: t('mailing_list.form.confirm_delete')}
.clearfix
= bootstrap_form_with(model: mailing_list, local: true) do |f|
  - if mailing_list.errors.any?
    #error_explanation
      %h2= t('mailing_list.form.errors_msg', count: mailing_list.errors.count)
      %ul
        - mailing_list.errors.full_messages.each do |message|
          %li= message
  = f.text_field :name, floating: true

  #emails
    = f.fields_for(:emails, mailing_list.emails, layout: :inline) do |email_form|
      = render partial: 'mailing_list_emails/form', locals: {f: email_form, mailing_list_email: email_form.object}
  .actions
    = link_to_add_fields(t('mailing_list.form.add_email'), f, :emails, {partial: 'mailing_list_emails/form', target: "#emails", locals: { mailing_list_email: f.object.emails.build }, layout: :inline}, class: 'btn btn-success', id: "add-email")
    = f.submit class: 'btn btn-primary'

app/views/mailing_lists/edit.haml
- title t('mailing_list.form.title.edit', name: @mailing_list.name)
%h1.title= t('mailing_list.form.header.edit', name: @mailing_list.name)
= render 'form', mailing_list: @mailing_list
= link_to t('form.show'), @mailing_list
|
= link_to t('back'), mailing_lists_path

app/views/mailing_lists/index.haml
- title t('mailing_list.index.title')
%h1.title= t('mailing_list.index.header')
%table.table
  %thead
    %tr
      %th= t('mailing_list.index.headings.name')
      %th= t('mailing_list.index.headings.emails_count')
      %th
  %tbody
    - @mailing_lists.each do |mailing_list|
      %tr
        %td= link_to mailing_list.name, mailing_list, class: 'is-size-5 is-link'
        %td= mailing_list.emails.count
        %td
          .btn-group
            = link_to t('form.edit'), edit_mailing_list_path(mailing_list), class: 'btn btn-primary btn-small'
            = link_to t('form.delete'), mailing_list, method: :delete, data: { confirm: t('form.confirm') }, class: 'btn btn-danger'
= link_to t('mailing_list.index.new_button'), new_mailing_list_path, class: ['btn', 'btn-primary']

app/views/mailing_lists/new.haml
- title t('mailing_list.form.title.new')
%h1.title= t('mailing_list.form.header.new')
= render 'form', mailing_list: @mailing_list
= link_to t('back'), mailing_lists_path, class: 'button is-white'

app/views/mailing_lists/show.haml
- title @mailing_list.name
.row
  .col-lg-6
    %h1.title
      = @mailing_list.name
      = link_to t('form.edit'), edit_mailing_list_path(@mailing_list)
    %table.table
      %thead
        %tr
          %td= t('mailing_list.show.headings.email')
          %td= t('mailing_list.show.headings.user')
      %tbody
        - @emails.each do |email|
          %tr
            %td= email.email
            - if email.user.present?
              %td= email.user.name
            - else
              %td.text-muted= t('mailing_list.show.no_user')
    %h4= t('mailing_list.show.copypastable')
    = text_area_tag nil, @emails.pluck(:email).join(",\n"), class: 'form-control'
  .col-lg-6
    %h2.text-center= t('mailing_list.show.manage')
    = button_to t('mailing_list.show.sync'), sync_users_mailing_list_path(@mailing_list), method: :put, class: 'btn btn-primary btn-block btn-sm'
    .row
      = form_tag '', class: 'form-inline col p-0', method: :get do
        = hidden_field_tag :scope, 'exclude_no_rsvps'
        .input-group.col
          .input-group-prepend
            .input-group-text= t('mailing_list.show.filters.exclude_no_for')
          = select_tag :event_id, options_for_select(Event.all.pluck(:title, :id)), class: 'form-control'
          = submit_tag "Filter", class: 'btn btn-primary col-auto m-0'
    .row
      = form_tag '', class: 'form-inline col p-0', method: :get do
        = hidden_field_tag :scope, 'attendees'
        .input-group.col
          .input-group-prepend
            .input-group-text= t('mailing_list.show.filters.attendees')
          = select_tag :event_id, options_for_select(Event.all.pluck(:title, :id)), class: 'form-control'
          = submit_tag t('mailing_list.show.filters.button'), class: 'btn btn-primary col-auto m-0'

    = link_to t('mailing_list.show.filters.clear'), mailing_list_path(@mailing_list), class: 'btn btn-secondary btn-block btn-sm'