config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)" do
    devise_for :users,
      controllers: {
        registrations: 'users/registrations',
      },
      defaults: {
        locale: I18n.locale,
      }

    resources :events, shallow: true do
      member do
        get 'ical'
      end

      collection do
        get 'rsvped', to: 'events#attendee_index'
      end

      resources :comments, only: [:create, :update, :destroy] do
        member do
          put 'undelete'
          post 'reply', to: 'comments#create_reply'
        end
      end

      resources :attendances, only: [:create, :update, :destroy]
      resources :polls, except: [:index, :show], shallow: true do
        resources :poll_responses, only: [:create, :update, :destroy]
      end
    end

    resources :addresses, only: [
      :show,
      # only for testing
      :create,
    ]


    # user-scoped events index
    resources :user, shallow: true, only: [] do
      resources :addresses, only: [:create]
      resources :events, only: [:index]
    end

    resources :mailing_lists do
      member do
        put 'sync_users'
      end
    end

    root "home#index"
  end
end

app/models/event.rb
class Event < ApplicationRecord
  extend FriendlyId
  include Ownable

  LANDING_PAGE_PHOTO_HEIGHT = 400

  TIMESTAMP_FORMAT = '%m/%d/%Y %l:%M %P'

  friendly_id :title, use: :history

  has_many :attendances, dependent: :destroy

  # photo for header of event, will be thumbnailed for index view
  has_one_attached :photo

  has_many :comments, dependent: :destroy
  has_many :polls, dependent: :destroy
  belongs_to :address

  accepts_nested_attributes_for :polls, allow_destroy: true
  accepts_nested_attributes_for :address

  validates :start_time, :end_time, presence: true

  validate :ends_after_it_starts

  validates_associated :address

  scope :secret, -> { where(secret: true) }
  scope :not_secret, -> { where(secret: false) }
  scope :attended_by, ->(user) { joins(:attendances).where(attendances: {attendee_id: user.id, attendee_type: "User"}) }

  def landing_page_photo
    photo.variant(resize: '1900', crop: "1900x500+0+#{header_photo_crop_y_offset}")
  end

  def header_photo_crop_y_offset
    if photo.metadata['width']
      width_scale = 1900.0 / photo.metadata['width']
    else
      puts photo.metadata
      width_scale = 1
    end
    photo_crop_y_offset * width_scale
  end

  def parse_time(timestamp)
    return timestamp if timestamp.is_a?(Time)

    return Time.zone.strptime(timestamp, TIMESTAMP_FORMAT)
  rescue ArgumentError
    nil
  end

  def start_time=(value)
    super(parse_time(value))
  end

  def start_time_str
    start_time.try(:strftime, TIMESTAMP_FORMAT)
  end

  def end_time=(value)
    super(parse_time(value))
  end

  def end_time_str
    end_time.try(:strftime, TIMESTAMP_FORMAT)
  end

  def allows_plus_ones?
    plus_one_max != 0
  end

  def has_plus_one_limit?
    allows_plus_ones? && plus_one_max > 0
  end

  def icalendar(event_url)
    cal = Icalendar::Calendar.new
    cal.prodid = "-//#{self.owner.name}//NONSGML ExportToCalendar//EN"
    cal.version = '2.0'
    cal.event do |e|
      e.dtstart = Icalendar::Values::DateTime.new(self.start_time)
      e.dtend = Icalendar::Values::DateTime.new(self.end_time)
      e.summary = self.title
      e.description = self.description
      e.url = event_url
      e.location = self.address.to_s
    end

    return cal
  end

  private

  def ends_after_it_starts
    return unless [end_time, start_time].all?
    unless end_time > start_time
      errors.add(:end_time, :ends_before_start)
    end
  end

  def should_generate_new_friendly_id?
    title_changed? || super
  end
end

app/controllers/api/events_controller.rb
module Api
  class EventsController < ApiController
    def index
      events = get_events_list

      current_scope = params[:scope] || "past"

      case current_scope
      when "past"
        events = events.where("end_time < ?", Time.current)
      else
        events = events.where("end_time > ?", Time.current)
      end

      events = events.order(end_time: :desc)

      render json: events
    end

    private

    def get_events_list
      events = Event.all.includes(:attendances, :owner)

      user_scoped_events_list(events, current_api_user)
    end

    # Hides all secret events except ones the user has already RSVPed to.
    # Obviously, unauthenticated users haven't RSVPed to any events.
    def user_scoped_events_list(events, viewing_user)
      if viewing_user
        events.left_joins(:attendances).where("NOT events.secret OR (attendances.attendee_id = ? and attendances.attendee_type = 'User')", viewing_user.id).distinct
      else
        events.not_secret
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :ical, :index, :attendee_index]
  before_action :set_event, only: [:show, :ical]
  before_action :set_owned_event, only: [:edit, :update, :destroy]
  before_action :load_prior_addresses, only: [:new, :edit, :create, :update]

  PRELOAD = [
    :address,
    :owner,
    {
      attendances: :attendee,
      comments: [:creator, :editor],
      photo_attachment: :blob,
      polls: :responses,
    },
  ]

  def index
    if params[:user_id]
      @host = User.friendly.find(params[:user_id])
      if current_user && current_user == @host
        @index_title = t('event.index.self')
      else
        @index_title = t('event.index.for_user', name: @host.name)
      end
    else
      @index_title = t('event.index.public')
    end

    @events, @current_scope = time_scoped_events_list(get_events_list_for(@host), params[:scope])
  end

  def attendee_index
    if @authenticated_user.nil?
      redirect_to events_url, notice: t('event.index.attending.auth_required')
      return
    end

    @index_title = t('event.index.attending.title')

    @events, @current_scope = time_scoped_events_list(@authenticated_user.rsvped_events, params[:scope])

    render :index
  end

  def show
    if @authenticated_user
      @attendee = @authenticated_user
      @attendance ||= @event.attendances.includes(:attendee, plus_ones: :attendee).find_by(attendee: @authenticated_user)
    end

    @attendance ||= @event.attendances.includes(:attendee).build
  end

  # get an ical event version of this event
  def ical
    send_data @event.icalendar(event_url(@event)).to_ical, type: 'text/calendar', filename: "#{@event.title}.ics"
  end

  def new
    @event = Event.new
    @event.build_address if @event.address.nil?
  end

  def edit
    @event.build_address if @event.address.nil?
  end

  def create
    @event = current_user.managed_events.build(event_params)

    if @event.save
      redirect_to @event, notice: t('event.created')
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: t('event.updated')
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: t('event.destroyed')
  end

  private

  def get_events_list_for(host)
    if host
      events = host.managed_events

      # users can see all their own events, so we short-circuit here for users
      # viewing their own events list to avoid any further filtering
      if @authenticated_user == host
        return events.includes(:attendances, :owner)
      end
    else
      events = Event.all
    end

    events = events.includes(:attendances, :owner)

    user_scoped_events_list(events, @authenticated_user)
  end

  def time_scoped_events_list(events, target_scope)
    case target_scope
    when "past"
      return [events.where("end_time <= ?", Time.current).order(end_time: :desc), "past"]
    else
      return [events.where("end_time > ?", Time.current).order(end_time: :desc), "future"]
    end
  end

  # Hides all secret events except ones the user has already RSVPed to.
  # Obviously, unauthenticated users haven't RSVPed to any events.
  def user_scoped_events_list(events, viewing_user)
    if viewing_user
      events.left_joins(:attendances).where("NOT events.secret OR (attendances.attendee_id = ? and attendances.attendee_type = 'User')", viewing_user.id).distinct
    else
      events.not_secret
    end
  end

  def set_event
    @event = EventDecorator.decorate(Event.includes(*EventsController::PRELOAD).friendly.find(params[:id]))
  end

  # ensures that the event being access is owned by the current user
  def set_owned_event
    @event = current_user.managed_events.includes(*EventsController::PRELOAD).friendly.find(params[:id])
  end

  def load_prior_addresses
    @prior_addresses = current_user.addresses
  end

  def event_params
    params.require(:event).permit(
      :title,
      :start_time,
      :end_time,
      :secret,
      :requires_testing,
      :description,
      :photo,
      :photo_crop_y_offset,
      :plus_one_max,
      :address_id,
      address_attributes: [
        :street,
        :street2,
        :city,
        :state,
        :zip_code
      ],
      polls_attributes: [
        :id,
        :_destroy,
        :question,
        {
          responses_attributes: [
            [:_destroy, :id, :example_response, :choice]
          ]
        }
      ]
    )
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def rsvps_order(attendances)
    attendances.includes(:attendee, parent_attendance: :attendee).sort_by do |attendance|
      [
        (attendance.parent_attendance.try(:attendee).try(:name) || attendance.attendee.name).downcase,
        attendance.attendance_id.present? ? '1' : '0',
        attendance.attendee.try(:name).try(:downcase),
      ]
    end
  end

  def rsvp_color_class(attendance)
    if attendance.attendance_id.present?
      'ms-5 list-group-item-info'
    elsif attendance.event.owned_by?(attendance.attendee)
      'list-group-item-primary'
    else
      ''
    end
  end

  def signup_sheet_color_class(signup_sheet_item)
    if signup_sheet_item.claimed?
      if signup_sheet_item.claimed_by?(user_or_guest)
        'list-group-item-primary'
      else
        'list-group-item-info'
      end
    else
      ''
    end
  end
end

app/views/events/_calendar_links.html.haml
- if event.attended_by?(attendee)
  .row.calendar-links
    .m-2.col-sm= link_to t('event.add_to_gcal'), gcal_url(event), class: 'text-decoration-none'
    .m-2.col-sm-auto= link_to t('event.download_ics'), ical_event_path(event), class: 'text-decoration-none'

app/views/events/_form.html.haml
= vite_typescript_tag 'events'
= vite_stylesheet_tag 'entrypoints/stylesheets/events.scss'

- # svg config for info circle
%svg.d-none{xmlns: "http://www.w3.org/2000/svg"}
  %symbol#info-fill{viewBox: "0 0 16 16", fill: 'currentColor'}
    %path{d: "M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"}

.accordion.p-1.mx-md-5
  .accordion-item
    .accordion-header.d-grid
      %button.accordion-button.collapsed.gap-2.btn.text-bg-secondary{type: 'button', data: {bs: {toggle: 'collapse', target: '#preview'}}, aria: {expanded: 'false', controls: 'preview'}}= t('event.form.preview_label')
    #preview.accordion-collapse.collapse
      .alert.alert-info.m-3.d-inline-flex.flex-shrink-0.align-items-center
        %svg.bi.flex-shrink-0.me-2{role: "img", width: '1em', height: '1em', aria: {label: "Info:"}}
          %use{'xlink:href' => "#info-fill"}
        %div= t('event.form.header_photo_crop_prompt')
      .hero.border-top
        .hero-image
          %img#photo-preview{src: event.photo.attached? ? rails_storage_redirect_path(event.photo) : vite_asset_path('images/default_event_image.jpg'), data: {initial_y_offset: event.photo_crop_y_offset}}
        .mx-2
          .hero-title
            %h1.title.display-4#title-preview{data: {default: t('event.title_placeholder')}}
            %em.text-muted.mb-2
              = t('event.show.hosted_by_you')
      .mx-1.alert.alert-danger.text-center.emojified-warning#requires-testing
        %strong= t('event.show.requires_testing')
%hr
= bootstrap_form_for(event, url: event.persisted? ? event_path(event) : events_path) do |form|
  = form.text_field :title, floating: true
  = form.form_group(class: 'mt-3 d-lg-flex') do
    .flex-lg-grow-1
      = form.text_field :start_time, class: 'datetimepicker', value: event.start_time_str, floating: true
    .align-items-center.text-center.mx-3
      %em.col= "…#{t('event.show.time_separator')}…"
    .flex-lg-grow-1
      = form.text_field :end_time, class: 'datetimepicker', value: event.end_time_str, floating: true
  .row
    .flex-grow-0.col-lg-6
      .input-group
        = form.check_box(:plus_one_max, {label: t('event.form.plus_ones_prompt'), label_class: 'btn btn-outline-dark', class: 'marked-checkbox btn-check', wrapper_class: 'input-group-text', id: 'event_plus_one_enable', checked: event.plus_one_max != 0}, -1, 0)
        = form.select :plus_one_max, [[t('event.form.plus_ones_unlimited'), -1], 1, 2, 3], class: 'pe-sm-3', selected: event.plus_one_max, floating: true
    .col-auto
      = form.check_box :secret, label_class: 'btn btn-outline-dark', class: 'marked-checkbox btn-check', wrapper_class: 'd-inline-block'
      = render "shared/info_tooltip", message: t('event.form.secret_event_help')
    .col-auto
      = form.check_box :requires_testing, label_class: 'btn btn-outline-dark', class: 'marked-checkbox btn-check', wrapper_class: 'd-inline-block'
      = render "shared/info_tooltip", message: t('event.form.testing_help')
  = form.form_group do
    = form.hidden_field :photo_crop_y_offset
    - if event.photo.attached?
      = form.hidden_field :photo, value: form.object.photo.signed_id
    = form.file_field :photo, direct_upload: true, help: t('event.form.header_photo_help')
    %strong.form-text#crop-prompt= t('event.form.header_photo_crop_prompt')
  = render partial: "addresses/form", locals: { parent_form: form, address: event.address }
  %hr
  .form-group
    = form.text_area :description, class: 'form-control', style: "height: 10em;", floating: true, help: t('event.form.description_uses_markdown_html', link: link_to(t('event.form.description_uses_markdown_name'), 'https://www.markdownguide.org/basic-syntax/'))
  %hr
  .form-group.mb-2
    %h3= Poll.model_name.human(count: 2)
    #polls
      = form.fields_for(:polls, layout: :inline) do |f|
        = render partial: "polls/form", locals: {f: f}
    = link_to_add_fields t('poll.add_prompt'), form, :polls, {partial: 'polls/form', target: "#polls", locals: { poll: form.object.polls.build }, layout: :inline, child_index: 'added_poll'}, class: 'btn btn-success', id: "add-poll"
  %hr
  .actions
    = form.primary
    = link_to t('back'), events_path, class: 'ms-2 btn btn-light'

app/views/events/_rsvps.html.haml
%h5.text-center.mt-2 Attendees
%ul.nav.nav-pills.nav-fill{role: 'tablist'}
  %li.nav-item
    %a.nav-link#going-tab{href: '#going', role: 'tab', 'aria-controls' => 'going', data: {'bs-toggle': 'tab'}}
      %i.fa.fa-check{"aria-hidden" => true}
      %span= t('event.rsvp_list.headers.yes', count: event.attendances.going.count)
  %li.nav-item
    %a.nav-link#maybe-tab{href: '#maybe', role: 'tab', 'aria-controls' => 'maybe', data: {'bs-toggle': 'tab'}}
      %i.fa.fa-question{"aria-hidden" => true}
      %span= t('event.rsvp_list.headers.maybe', count: event.attendances.maybe.count)
  %li.nav-item
    %a.nav-link#not-going-tab{href: '#not-going', role: 'tab', 'aria-controls' => 'not-going', data: {'bs-toggle': 'tab'}}
      %i.fa.fa-cross{"aria-hidden" => true}
      %span= t('event.rsvp_list.headers.no', count: event.attendances.not_going.count)
.tab-content
  - {going: event.attendances.going, maybe: event.attendances.maybe, 'not-going': event.attendances.not_going}.each do |label, collection|
    - attendances_ordered = rsvps_order(collection)
    .tab-pane{id: label, role: 'tabpanel', 'aria-labelledby' => "#{label}-tab"}
      %ul.list-group
        - if attendances_ordered.empty?
          %li.list-group-item
            %small.text-muted= t('event.rsvp_list.empty_category')
        - elsif event.owned_by?(current_user)
          %li.list-group-item
            %div.mb-2
              %strong= t('event.rsvp_list.host_email_collection_header')
              = text_area_tag nil, attendances_ordered.map(&:attendee).pluck(:email).join(",\n"), class: 'form-control'
        = render partial: "attendances/attendance", collection: attendances_ordered

app/views/events/edit.html.haml
- title t('event.form.title.edit', title: @event.title)
= render 'form', event: @event

app/views/events/index.html.haml
- title @index_title
%h1.title
  = @index_title
  .btn-group{role: "group", "aria-label" => "event scopes"}
    = scope t('event.index.category.upcoming'), url_for(scope: :future), :future
    = scope t('event.index.category.past'), url_for(scope: :past), :past
- if @events.any?
  - @events.each do |event|
    .row.bg-light.mb-2.py-2
      .col.align-middle
        .d-grid.text-center
          = link_to event.title, event, class: 'h3 p-2 text-decoration-none'
          - if event.secret
            %small.fst-italic.float-end= t('event.index.labels.secret')
        - if @host.nil?
          %small.fst-italic.mx-2= t('event.index.hosted_by', name: event.hosts_list_str)
        %small.d-block.float-sm-end.mx-2.fw-bold= EventDecorator.decorate(event).start_date
      .col-auto
        .d-grid.gap-1
          .badge.bg-success{title: t('event.index.labels.going'), data: {'bs-toggle': 'tooltip'}}= event.attendances.pluck(:rsvp_status).count('Yes')
          .badge.bg-warning{title: t('event.index.labels.maybe'), data: {'bs-toggle': 'tooltip'}}= event.attendances.pluck(:rsvp_status).count('Maybe')
      - if event.hosted_by?(current_user)
        .d-grid.gap-1
          = link_to t('form.edit'), edit_event_path(event), class: 'btn btn-primary btn-sm'
          - if event.owned_by?(current_user)
            = link_to t('form.delete'), event, method: :delete, data: { confirm: t('form.confirm') }, class: 'btn btn-danger btn-sm'
- else
  %p
    %strong= t('event.index.zero_state.message')
  - if @host
    - if @host == current_user
      %p= t('event.index.zero_state.click_to_make')
    - else
      %p= t('event.index.zero_state.other_user')
  - elsif @current_scope
    - if @current_scope == "future"
      %p= t('event.index.zero_state.past_prompt', past_link: link_to(t('event.index.zero_state.past_events'), events_path(scope: 'past'))).html_safe
    - elsif @current_scope == "past"
      %p= t('event.index.zero_state.upcoming_prompt', upcoming_link: link_to(t('event.index.zero_state.upcoming_events'), events_path(scope: 'future'))).html_safe
- if current_user
  - if current_user == @host
    - link_text = t('event.index.new_button.self')
  - else
    - link_text = t('event.index.new_button.other')

  = link_to link_text, new_event_path, class: ['btn', 'btn-primary']

app/views/events/new.html.haml
- title t('event.form.title.new')
= render 'form', event: @event

app/views/events/show.html.haml
= vite_typescript_tag 'comments'
- title @event.title

= content_for :edge_to_edge do
  .hero
    .hero-image
      - if @event.photo.attached?
        = image_tag rails_storage_redirect_path(@event.landing_page_photo)
      - else
        = image_tag 'default_event_image.jpg'
    .mx-2
      .hero-title
        %h1.title.display-4
          = @event.title
          - if @event.owned_by?(current_user)
            %small
              = link_to t('form.edit'), edit_event_path(@event), class: 'text-muted'
        %em.text-muted.mb-2
          - if @event.owned_by?(current_user)
            = t('event.show.hosted_by_you')
          - else
            = t('event.show.hosted_by_other', name: @event.owner.name)
- if @event.requires_testing
  .alert.alert-danger.text-center.emojified-warning
    %strong= t('event.show.requires_testing')
.row
  .col-lg.order-lg-1.order-sm-2
    .row
      .col-sm
        %em
          - # show a simplified format for events spanning a single day
          - if @event.start_datetime.to_date == @event.end_datetime.to_date
            .font-weight-bold= @event.start_date
            = "#{@event.start_time} - #{@event.end_time}"
          - else
            %strong= @event.start_date
            = @event.start_time
            %p
              = "…#{t('event.show.time_separator')}"
              %strong= @event.end_date
              = @event.end_time
      - if @event.address
        .col-sm-auto
          .d-sm-none.mt-2= render 'addresses/show', address: @event.address
          .d-none.d-sm-inline.text-end= render 'addresses/show', address: @event.address
    %hr
    .content= @event.description
  .col-lg.order-lg-2.order-sm-1
    = render 'attendances/event_form', attendance: @attendance, event: @event, attendee: @attendee
    = render 'events/calendar_links', attendee: @attendee, event: @event
    %hr
    = render 'events/rsvps', event: @event
    - if @event.polls.any?
      %hr
      - @event.polls.each do |poll|
        = render 'polls/poll', poll: poll, respondent: @attendee
%hr

= render @event.root_comments, comments: @event.comments
- if @authenticated_user
  %a.btn.btn-sm.btn-primary.comment-button.mb-3{data: {id: 'new'}}= t('comment.actions.new')
  .comment-form{data: {id: 'new'}}
    = render 'comments/form', event: @event